# Generated by Django 4.0.2 on 2022-02-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_billing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='insurance_comapny',
            new_name='insurance_comapany',
        ),
    ]
