# Generated by Django 4.0.2 on 2022-03-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_rename_insurance_comapany_billing_insurance_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='credit_card',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='billing',
            name='cvv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='billing',
            name='member_id',
            field=models.IntegerField(),
        ),
    ]
