# Generated by Django 4.0.2 on 2022-03-03 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_medical_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role_Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField()),
                ('delete', models.BooleanField()),
                ('date_of_change', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.users')),
            ],
        ),
    ]
