# Generated by Django 4.0.2 on 2022-03-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
