# Generated by Django 4.0.2 on 2022-03-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_device_thermometer_device_blood_pressure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_blood_pressure',
            old_name='bp',
            new_name='blood_pressure',
        ),
    ]
